[project]
name = "mmm-mcp"
version = "0.1.0"
description = "Michael's Magic Music MCP"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "fastmcp<3",
    "httpx>=0.28.1",
    "httpx-retries>=0.4.5",
]
